# Generated by Django 3.1.3 on 2021-01-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='telephone',
        ),
    ]
