# Generated by Django 3.1.3 on 2021-02-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(blank=True, to='pizza_app.Pizza'),
        ),
        migrations.DeleteModel(
            name='OrderPizza',
        ),
    ]
