# Generated by Django 3.1.3 on 2021-02-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_auto_20210208_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
