# Generated by Django 3.1.3 on 2021-01-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0003_userprofile_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
