# Generated by Django 3.1.3 on 2021-02-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0003_auto_20210209_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='line_topping',
            field=models.ManyToManyField(blank=True, to='pizza_app.Topping'),
        ),
    ]
