# Generated by Django 3.1.3 on 2021-02-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0004_lineitem_line_topping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='line_topping',
        ),
    ]
