# Generated by Django 3.1.3 on 2021-02-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0004_auto_20210208_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='user',
        ),
    ]
