# Generated by Django 3.1.3 on 2021-02-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0005_remove_lineitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
