# Generated by Django 3.1.3 on 2021-02-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0006_lineitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pizzas',
        ),
    ]
