# Generated by Django 3.1.3 on 2021-02-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0007_remove_order_pizzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='line_items_total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
