# Generated by Django 3.1.3 on 2021-02-08 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0008_order_line_items_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='quantity',
        ),
    ]
