# Generated by Django 3.1.3 on 2021-01-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0019_remove_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='pizza_id',
        ),
    ]
